twig:
    file_name_pattern: '*.twig'
    form_themes: ['admin/form/tema_tailwind.html.twig']
    date:
        format: 'd/m/Y'
        timezone: 'America/Sao_Paulo'
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'

when@test:
    twig:
        strict_variables: true
