<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260927150319 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Estrutura inicial: cadastros, ponto, justificativas, fechamento e auxílio-transporte';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cargo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(120) NOT NULL, salario_base NUMERIC(10, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3BEE577154BD530C ON cargo (nome)');
        $this->addSql('CREATE TABLE fechamento_competencia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, competencia VARCHAR(7) NOT NULL, fechado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fechado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A100682842C498A ON fechamento_competencia (competencia)');
        $this->addSql('CREATE INDEX IDX_6A100682A8291057 ON fechamento_competencia (fechado_por_id)');
        $this->addSql('CREATE TABLE feriado (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data DATE NOT NULL, descricao VARCHAR(120) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D864013ADF3F363 ON feriado (data)');
        $this->addSql('CREATE TABLE funcionario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, matricula VARCHAR(20) NOT NULL, nome VARCHAR(150) NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, jornada_diaria_minutos SMALLINT NOT NULL, data_admissao DATE NOT NULL, ativo BOOLEAN NOT NULL, cargo_id INT NOT NULL, setor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7510A3CF15DF1885 ON funcionario (matricula)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7510A3CFE7927C74 ON funcionario (email)');
        $this->addSql('CREATE INDEX IDX_7510A3CF813AC380 ON funcionario (cargo_id)');
        $this->addSql('CREATE INDEX IDX_7510A3CF4D94F126 ON funcionario (setor_id)');
        $this->addSql('CREATE TABLE justificativa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data DATE NOT NULL, tipo VARCHAR(30) NOT NULL, motivo TEXT NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, avaliado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, observacao_avaliacao TEXT DEFAULT NULL, funcionario_id INT NOT NULL, avaliado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_justificativa_funcionario_data ON justificativa (funcionario_id, data)');
        $this->addSql('CREATE INDEX IDX_2D80E128642FEB76 ON justificativa (funcionario_id)');
        $this->addSql('CREATE INDEX IDX_2D80E1284095E237 ON justificativa (avaliado_por_id)');
        $this->addSql('CREATE TABLE linha_onibus (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, codigo VARCHAR(20) NOT NULL, nome VARCHAR(150) NOT NULL, tarifa NUMERIC(8, 2) NOT NULL, ativa BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D5C41F0E20332D99 ON linha_onibus (codigo)');
        $this->addSql('CREATE TABLE registro_ponto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, momento TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, funcionario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_ponto_funcionario_momento ON registro_ponto (funcionario_id, momento)');
        $this->addSql('CREATE INDEX IDX_2ED7D752642FEB76 ON registro_ponto (funcionario_id)');
        $this->addSql('CREATE TABLE setor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(120) NOT NULL, sigla VARCHAR(20) NOT NULL, chefe_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B3ECDC7801B7D4B ON setor (sigla)');
        $this->addSql('CREATE INDEX IDX_7B3ECDC758AC7DA4 ON setor (chefe_id)');
        $this->addSql('CREATE TABLE solicitacao_auxilio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, avaliado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, observacao_avaliacao TEXT DEFAULT NULL, funcionario_id INT NOT NULL, avaliado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_830331E7642FEB76 ON solicitacao_auxilio (funcionario_id)');
        $this->addSql('CREATE INDEX IDX_830331E74095E237 ON solicitacao_auxilio (avaliado_por_id)');
        $this->addSql('CREATE TABLE trajeto_auxilio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sentido VARCHAR(10) NOT NULL, solicitacao_id INT NOT NULL, linha_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4152AA32774BE1CF ON trajeto_auxilio (solicitacao_id)');
        $this->addSql('CREATE INDEX IDX_4152AA327D6EBD49 ON trajeto_auxilio (linha_id)');
        $this->addSql('ALTER TABLE fechamento_competencia ADD CONSTRAINT FK_6A100682A8291057 FOREIGN KEY (fechado_por_id) REFERENCES funcionario (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE funcionario ADD CONSTRAINT FK_7510A3CF813AC380 FOREIGN KEY (cargo_id) REFERENCES cargo (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE funcionario ADD CONSTRAINT FK_7510A3CF4D94F126 FOREIGN KEY (setor_id) REFERENCES setor (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE justificativa ADD CONSTRAINT FK_2D80E128642FEB76 FOREIGN KEY (funcionario_id) REFERENCES funcionario (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE justificativa ADD CONSTRAINT FK_2D80E1284095E237 FOREIGN KEY (avaliado_por_id) REFERENCES funcionario (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE registro_ponto ADD CONSTRAINT FK_2ED7D752642FEB76 FOREIGN KEY (funcionario_id) REFERENCES funcionario (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE setor ADD CONSTRAINT FK_7B3ECDC758AC7DA4 FOREIGN KEY (chefe_id) REFERENCES funcionario (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE solicitacao_auxilio ADD CONSTRAINT FK_830331E7642FEB76 FOREIGN KEY (funcionario_id) REFERENCES funcionario (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE solicitacao_auxilio ADD CONSTRAINT FK_830331E74095E237 FOREIGN KEY (avaliado_por_id) REFERENCES funcionario (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trajeto_auxilio ADD CONSTRAINT FK_4152AA32774BE1CF FOREIGN KEY (solicitacao_id) REFERENCES solicitacao_auxilio (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trajeto_auxilio ADD CONSTRAINT FK_4152AA327D6EBD49 FOREIGN KEY (linha_id) REFERENCES linha_onibus (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fechamento_competencia DROP CONSTRAINT FK_6A100682A8291057');
        $this->addSql('ALTER TABLE funcionario DROP CONSTRAINT FK_7510A3CF813AC380');
        $this->addSql('ALTER TABLE funcionario DROP CONSTRAINT FK_7510A3CF4D94F126');
        $this->addSql('ALTER TABLE justificativa DROP CONSTRAINT FK_2D80E128642FEB76');
        $this->addSql('ALTER TABLE justificativa DROP CONSTRAINT FK_2D80E1284095E237');
        $this->addSql('ALTER TABLE registro_ponto DROP CONSTRAINT FK_2ED7D752642FEB76');
        $this->addSql('ALTER TABLE setor DROP CONSTRAINT FK_7B3ECDC758AC7DA4');
        $this->addSql('ALTER TABLE solicitacao_auxilio DROP CONSTRAINT FK_830331E7642FEB76');
        $this->addSql('ALTER TABLE solicitacao_auxilio DROP CONSTRAINT FK_830331E74095E237');
        $this->addSql('ALTER TABLE trajeto_auxilio DROP CONSTRAINT FK_4152AA32774BE1CF');
        $this->addSql('ALTER TABLE trajeto_auxilio DROP CONSTRAINT FK_4152AA327D6EBD49');
        $this->addSql('DROP TABLE cargo');
        $this->addSql('DROP TABLE fechamento_competencia');
        $this->addSql('DROP TABLE feriado');
        $this->addSql('DROP TABLE funcionario');
        $this->addSql('DROP TABLE justificativa');
        $this->addSql('DROP TABLE linha_onibus');
        $this->addSql('DROP TABLE registro_ponto');
        $this->addSql('DROP TABLE setor');
        $this->addSql('DROP TABLE solicitacao_auxilio');
        $this->addSql('DROP TABLE trajeto_auxilio');
    }
}
