<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261007044212 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE registro_auditoria (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ocorrido_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, autor_nome VARCHAR(150) NOT NULL, acao VARCHAR(20) NOT NULL, entidade VARCHAR(60) NOT NULL, entidade_id VARCHAR(40) NOT NULL, rotulo VARCHAR(200) NOT NULL, alteracoes JSON NOT NULL, ip VARCHAR(45) DEFAULT NULL, autor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_auditoria_ocorrido_em ON registro_auditoria (ocorrido_em)');
        $this->addSql('CREATE INDEX idx_auditoria_entidade ON registro_auditoria (entidade, entidade_id)');
        $this->addSql('CREATE INDEX IDX_3A5B2C9514D45BBE ON registro_auditoria (autor_id)');
        $this->addSql('ALTER TABLE registro_auditoria ADD CONSTRAINT FK_3A5B2C9514D45BBE FOREIGN KEY (autor_id) REFERENCES funcionario (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE registro_auditoria DROP CONSTRAINT FK_3A5B2C9514D45BBE');
        $this->addSql('DROP TABLE registro_auditoria');
    }
}
